# Generated by Django 4.2.1 on 2023-05-31 01:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('account', '0018_alter_mechanic_mechanic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('garage_id', models.AutoField(primary_key=True, serialize=False)),
                ('garage_name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garagesregist.garage')),
                ('services_name', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
