# Generated by Django 4.1.7 on 2023-04-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customer_id_customer_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='phone_number',
            field=models.CharField(default='08xxxxxxxxxx', max_length=15),
        ),
    ]
