# Generated by Django 4.1.7 on 2023-05-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_mechanic_location_coordinates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanic',
            old_name='user_id',
            new_name='mechanic_id',
        ),
        migrations.RenameField(
            model_name='mechanic',
            old_name='owner_name',
            new_name='mechanic_name',
        ),
        migrations.RenameField(
            model_name='mechanic',
            old_name='owner_nik',
            new_name='mechanic_nik',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='garage_name',
        ),
    ]
