# Generated by Django 4.1.7 on 2023-05-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_user_id_mechanic_mechanic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='mechanic_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='mechanic_nik',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
