# Generated by Django 4.1.7 on 2023-05-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_mechanic_mechanic_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanic',
            old_name='mechanic_id',
            new_name='user_id',
        ),
    ]
