# Generated by Django 4.1.7 on 2023-05-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_mechanic_id_mechanic_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='user_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
