# Generated by Django 4.1.7 on 2023-05-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customer_user_id_alter_mechanic_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
