# Generated by Django 4.2.1 on 2023-05-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_customer_user_id_alter_mechanic_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
