# Generated by Django 4.2.1 on 2023-05-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_mechanic_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='mechanic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
