# Generated by Django 4.2.1 on 2023-05-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_mechanic_mechanic_nik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='mechanic_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='mechanic_nik',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
